name = "minimo"
license = "MIT"
description = "A lightweight and blazing fast personal website theme"
homepage = "#github link here"
features = ["responsive", "gallery", "multilingual"]
tags = ["fast", "responsive", "bootstrap", "personal"]

[author]
  name = "Wiley McKay Conte"
  homepage = "https://wileys.Website"

[original]
  name = "Gökmen Görgen"
  homepage = "https://gokmengorgen.net"
  repo = "https://github.com/gkmngrgn/hugo-alageek-theme"
