baseURL = "https://example.com"
title = "Your Awesome Website"
theme = "minimo"
paginate = 3

[params]
logofile = "wileys.website/img/Robobrand.png"
faviconfile = "wileys.website/img/Robobrand.png"
copyright = "Wiley McKay Conte 2018"
github = "wileybaba"
email = "baba@example.com"
twitter = "wiley_baba"
instagram = "wileybaba"
fork = "github.com/wileybaba/minimo_hugo_theme"
progressively = true

defaultContentLanguage = 'en'

[[params.portfolio]]

link = ""
